apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-x1
  namespace: vm-ns-1
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: rhel9-x1
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 22Gi
        storageClassName: ocs-storagecluster-ceph-rbd-virtualization
        volumeMode: Block
      source:
        snapshot:
          name: rhel9-vm-ns-1
          namespace: vm-ns-1
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel9
    spec:
      nodeSelector:
        kubernetes.io/hostname: e45-h10-000-r650
      architecture: amd64
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: vda
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
        machine:
          type: pc-q35-rhel9.6.0
        memory:
          guest: 1Gi
        resources: {}
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: rhel9-x1
        name: vda
