apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kube-descheduler-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry-proxy.engineering.redhat.com/rh-osbs/iib-pub:v4.20 
  displayName: KDO
  publisher: Red Hat
