apiVersion: v1
data:
  ca-bundle.crt: | 
    -----BEGIN CERTIFICATE-----
    MIIGYzCCBEugAwIBAgIED/0Q3TANBgkqhkiG9w0BAQsFADBNMRAwDgYDVQQKEwdS
    ZWQgSGF0MQ0wCwYDVQQLEwRwcm9kMSowKAYDVQQDEyEyMDIzIENlcnRpZmljYXRl
    IEF1dGhvcml0eSBSSENTdjIwHhcNMjUwNzA5MDg0MTAzWhcNMjYwNzA0MDg0MTAz
    WjCBzzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
    VQQHDAdSYWxlaWdoMRAwDgYDVQQKDAdSZWQgSGF0MR4wHAYDVQQLDBVDb250YWlu
    ZXItQnVpbGQtR3VpbGQxMzAxBgkqhkiG9w0BCQEWJGNvbnRhaW5lci1idWlsZHN5
    cy1hbGVydHNAcmVkaGF0LmNvbTEuMCwGA1UEAwwlcmVnaXN0cnktcHJveHkuZW5n
    aW5lZXJpbmcucmVkaGF0LmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
    ggIBANk8qYYh3Icj1Orn1AtICEwD/y8GDZOqfu4TDvSdg6D1oK3eL1XzzdyAolhp
    Ft/2WACmte8QzADjAj1yn2dGwXOLnmVg+sxpW4Pgt5TrtGFzwwCweFRaVNk4aBZV
    Cuw9+0RNvE0MHRQ6njsTv694DHKKqsTuegrQ8HEfMiCwvvxwC08p0eOe0yh1Esl+
    X3zfQjB3fS6I0TpuMC4+69EPGrGiKRUSyXiILHATGmzAWaKeyCQvXAlJCjIb9ra9
    8ZkbIVLauxnlRnArB2BodKO7KEZCG3FTfxadWm9E45qdllKyLKWIgbCKhijdXpDd
    gsoLlLBsnQFykP0JytGMRpFEIw7V7pNLTrRm9nss33FHsCi36TRw1l3wujoRlrDP
    s7YoKoh8IiVGtzKjDOwdnCKSstVK3t4CzAL7ZdR0L4qLo+f+6+pwDkSWgnNtwup+
    cQWDDSnWLKmlhMECLTLtz4tXpiArlaVsZPBeyEqI5cUZhwOLCJNYrmrRFzqy1MZ0
    +PVtaHjeNtgnPDcQiV5pYFawREdkmFq1WycDrzQ5qbYpg/2m6GGz1o3oZofIffht
    f723WG06NsmYGczB9KTG0h85YECogJmtzn8ALhEkxDorzPVGzbVsA8oA9JLhKXOx
    BrkGb9zQwNONrpscih+GczfOUPWc3Yvje7nijh0ZB+5KlxkXAgMBAAGjgccwgcQw
    MAYDVR0RBCkwJ4IlcmVnaXN0cnktcHJveHkuZW5naW5lZXJpbmcucmVkaGF0LmNv
    bTAfBgNVHSMEGDAWgBQHTovJkcFa2TsMFGmZD+qHIJaF+jBABggrBgEFBQcBAQQ0
    MDIwMAYIKwYBBQUHMAGGJGh0dHA6Ly9vY3NwLmNvcnAucmVkaGF0LmNvbS9jYS9v
    Y3NwLzAOBgNVHQ8BAf8EBAMCBPAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
    BwMCMA0GCSqGSIb3DQEBCwUAA4ICAQBymkvNTtKuov72TsMJ/z2GUYP8ja0BovcF
    GQrkdwmmGLEjFgb+sKy0cjfT6AzhOXiox9J1N+pNXk/yDiLO/OT9Vb19K33nTUzP
    6DVCo3KvSSgd/sez6wiIrp90h5TRZLdICntySogaWk/lxap29KsQFNzALwOYJjwJ
    avfOT8XHk38gNwFAcXq49vG7500dneHPTwQZWZo+K662e8wsdX4GDP5rk7YIggHR
    9RgFIfnSexTOc9rsGqpSi6TjrSblHxk1fWawamPA3bx1YdIEzTdxCvQYPphg6f1j
    3sQ8YJsQ6YMk/XIcSxoAc0+kHcQALoZeQCQFb+L4Y27GHeUL0xxhq3l7BveOA0L2
    QuFN4cOsMOs6hoAlNX61OfrUwqQZPODbNZdYebbFn8XX0NSO0vZBlnTM8HTFRUde
    K5Yr+88DlbPSCWjiw5fxET4LB4CAWsc46zfnySEDU4X9HfH4i75srQcJJj6gzBQB
    lVd77+1cLzCKLCedkNzvoVfvpJn0VU5k8FPGoh1C8+3RnI1HC1Pj1+d3pedXHerY
    ox3XeRq47OQd2dgOxhSuJ8k6LQb51y396TIiazzTZvAZMR5ZQqHPrKFoKDH48Iym
    VNipQ16T1nK15+svswlRN7rzJGAcbA/eHG7QMplF+XUjEs6DT8ePzxofnjwi/4wd
    mED+3ak9eA==
    -----END CERTIFICATE----- 
kind: ConfigMap
metadata:
  name: user-ca-bundle-proxy-registry 
  namespace: openshift-config 
