{
 "title": "OpenShift Virtualization Performance",
 "description": "OCP Virt related performance metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "OpenShift Virtualization Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "HCO System",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_hco_system_health_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HCO Operator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_hyperconverged_operator_health_status{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Created VMs",
   "type": "stat",
   "description": "The total number of VMs that's being created. Including non-running VMs",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kubevirt_number_of_vms)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cnv:vmi_status_running:count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Request ",
   "type": "stat",
   "description": "The sum of all VM's CPU request",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster:vmi_request_cpu_cores:sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM Request",
   "type": "stat",
   "description": "The sum of all VM's RAM request",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vm_resource_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virt API Pod Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kubevirt_virt_api_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Pod Memory Usage/Request Delta ",
   "type": "stat",
   "description": "The delta between the pod with highest memory working set or rss and its requested memory for each container, virt-controller, virt-handler, virt-api and virt-operator. ",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_memory_delta_from_requested_bytes) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Virt Launcher Memory Overhead",
   "type": "stat",
   "description": "Average memory overhead per VM - The estimation of the memory amount required for virt-launcher’s infrastructure components (e.g. libvirt, QEMU)",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_launcher_memory_overhead_bytes{}) / count (kubevirt_vmi_launcher_memory_overhead_bytes{})",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "CNV System Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod!~\"virt-launcher.*\", namespace=\"openshift-cnv\", container!=\"\" }) by (pod)",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "CNV System Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!~\"virt-launcher.*\", namespace=\"openshift-cnv\", container!=\"\"}[1m])) by (pod)",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_rss{pod=~\"virt-launcher.*\", container!=\"\"}) by (pod), \"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\")",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{pod=~\"virt-launcher.*\", container!=\"\"}[1m])) by (pod),\"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\")",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "Node Available Memory Pecentage",
   "type": "timeseries",
   "description": "The percentage of avaiable memory listed by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{}) by (instance) / sum(node_memory_MemTotal_bytes{}) by (instance) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Ultilization ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[5m])) by (instance)",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "VMI Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_storage_iops_read_total[60s])) by (name)",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "VMI Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": " sum(rate(kubevirt_vmi_storage_iops_write_total[60s])) by (name)",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "VMI Storage Read Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_storage_read_traffic_bytes_total[60s])) by (name)",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "VMI Storage Write Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_storage_write_traffic_bytes_total[60s])) by (name)",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "VMI Network Traffic Recevied ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_network_receive_bytes_total[60s])) by (name)",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "VMI Network Traffic Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vmi_network_transmit_bytes_total[60s])) by (name)",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  { "title": "Migration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_migration_succeeded)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduling ",
   "type": "stat",
   "description": "Migration in Scheduling phase",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_migrations_in_scheduling_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running ",
   "type": "stat",
   "description": "Migration in running phase",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_migrations_in_running_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "description": "Migration in pending phase",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_migrations_in_pending_phase)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}