apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {VM_BASENAME}-base
  namespace: {vm-ns}
spec:
  source:
      http:
        url: {DV_URL}
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: {STORAGE_SIZE}
    volumeMode: Block
    storageClassName: {STORAGE_CLASS}
