apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-fio
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: rhel9-fio
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 23Gi
        volumeMode: Block
        storageClassName: ocs-storagecluster-ceph-rbd-virtualization
      source:
        pvc:
          name: rhel9-placeholder 
          namespace: default
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel9
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 2
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: vda
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
        resources:
          requests:
            memory: 8Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: rhel9-fio 
        name: vda
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            runcmd:
              - echo "=== Cloud-init script starting at $(date) ===" | tee /var/log/fio-debug.log
              - echo "Current user: $(whoami)" | tee -a /var/log/fio-debug.log
              - echo "Current directory: $(pwd)" | tee -a /var/log/fio-debug.log
              - echo "Testing network connectivity..." | tee -a /var/log/fio-debug.log
              - ping -c 3 10.6.67.194 2>&1 | tee -a /var/log/fio-debug.log
              - echo "Testing HTTP connectivity..." | tee -a /var/log/fio-debug.log
              - curl -I http://10.6.67.194:8081/fio.sh 2>&1 | tee -a /var/log/fio-debug.log
              - echo "Downloading fio.sh script..." | tee -a /var/log/fio-debug.log
              - curl -v -o /root/fio.sh http://10.6.67.194:8081/fio.sh 2>&1 | tee -a /var/log/fio-debug.log
              - echo "Download completed with exit code: $?" | tee -a /var/log/fio-debug.log
              - ls -la /root/fio.sh 2>&1 | tee -a /var/log/fio-debug.log
              - echo "File contents preview:" | tee -a /var/log/fio-debug.log
              - head -10 /root/fio.sh 2>&1 | tee -a /var/log/fio-debug.log
              - chmod +x /root/fio.sh 2>&1 | tee -a /var/log/fio-debug.log
              - echo "Executing fio.sh script..." | tee -a /var/log/fio-debug.log
              - cd /root && ./fio.sh 2>&1 | tee -a /var/log/fio-debug.log
              - echo "=== Cloud-init script completed at $(date) ===" | tee -a /var/log/fio-debug.log
              - curl -o /root/fio.sh http://10.6.67.194:8081/fio.sh
              - chmod +x /root/fio.sh
              - cd /root
              - ./fio.sh
